# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2026 Zulfikar Aji Kusworo (zakusworo) <greataji13@gmail.com>

[Service]
Environment=G_RESOURCE_OVERLAYS=/org/gnome/gmobile/devices/display-panels=/usr/share/gmobile/devices/display-panels
